### PR TITLE
add isEmptyTranslatableAttribute() to allow custom decision logic

### LINKED ISSUE #393: getAttributeOrFallback() method is doing weak comparisons to assess if a value is set, causing problems with booleans and integers
I'm using attribute fallbacks with my models, and am having problems when the attributes are cast as `boolean` or when the attribute can be an `int` with a value of `0`.

In `Translatable.php`, the following function gets the attribute or fallback if the attribute doesn't exist:

```
    /**
     * Returns the attribute value from fallback translation if value of attribute
     * is empty and the property fallback is enabled in the configuration.
     * in model.
     * @param $locale
     * @param $attribute
     * @return mixed
     */
    private function getAttributeOrFallback($locale, $attribute)
    {
        $value = $this->getTranslation($locale)->$attribute;

        $usePropertyFallback = $this->useFallback() && $this->usePropertyFallback();
        if (empty($value) && $usePropertyFallback) {
            return $this->getTranslation($this->getFallbackLocale(), true)->$attribute;
        }

        return $value;
    }
```

I think there are three problems here:

1. The function checks `if (empty($value) ...`, which causes a `boolean` with a value of `false` or an `integer` with a value of `0` to be considered "empty". Really, these could be valid attribute values on a translated model. Shouldn't an `isset()` check or something be done instead?
2. If trying to access a property like one described above on a translated model, but no fallback translation is available, a PHP error is thrown. I would have thought that if the property didn't exist on the fallback translation (i.e. because the fallback doesn't exist), the original value should be returned back? Again, because the original value could be valid in some cases (see point 1), but also because if there's no fallback available, a PHP error is thrown instead.
3. The function is private, so I can't override it to fix the issue for my own use case

Is my understanding of this situation correct? I may be missing something here so was a bit hesitant to put in a pull request without double-checking.

### LINKED ISSUE #543: Number zero will wrong translated
Hi all

I have to two languages and the fallback language is english. This package can not translate a zero as number(string).

Database:
screen shot 2019-01-24 at 11 40 05

Tinker:
```
>>> app()->setLocale('de');
=> null
>>> AttributeValue::find(14)->value;
=> "naanaa"
```

If i change the zero number it will be work.

### LINKED ISSUE #573: Fallback to default locale with numeric field is not working as expected
First of all, congrats and thanks for this great package!

You must be wondering why to translate a number: what I'm trying to achieve is to track the completion of translations with a boolean (tinyint) field, which is translatable. When the user has finished the translation of that article, he will check the "translation is ready". The best place to store that field is into the translation itself. So, we're translating a number, but it doens't work when translation fallback is active. It shows always the value of the main record, no matter what value is stored into the DB.

To reproduce the issue:

- Translation fallback is active.
- I create a record in the default language, and assign a value to this field, let's say 1.
- I create a new record in another language, and assign a value 0 to this field. This last value is stored correctly into the DB.
- When I edit this last record again, the fallback is triggered, when it shouldn't (because this record has already a translation), and brings the value 1 (from the record we first created), when it should be the  0 stored in the DB.

Strangely, the same happens when I use a text field and the value is numeric. The fallback fills this field with the value stored in the original language (even when the translation exists).

As a workaround I'm using a text field with "y" or "n" and everything works fine.
Did anyone find this problem?

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #393 
fixes #543 
fixes #573

### CODE REVIEW

**Comment by Gummibeer** [comment]
and this is how it looks if you don't want to run local CircleCI cli. 🙈 😂

**Comment by dimsav** [comment]
@Gummibeer I'm trying to understand why [this](https://github.com/dimsav/laravel-translatable/pull/576/files#diff-04265865db51c0afd103425e05a2abe2R200) change fixes the bug. Can you please explain?

Also, the first argument ($key) is never used. Why do we need it in `isEmptyTranslatableAttribute()`?

**Comment by Gummibeer** [comment]
@dimsav I see no way to cover all possible cases in this package with a single comparison - all will fail in some circumstances.
Putting the check in a special method which provides `$key` and `$value` allows the user to put in his custom logic which can also differ by attribute name and can also combine multiple checks like `is_null($value) || $value === ''`.
So this is primary the solution to give the user the tools and ability to adjust the logic.

**Comment by dimsav** [comment]
Love it. Good to go. 👌

**Comment by Gummibeer** [comment]
https://github.com/dimsav/laravel-translatable/releases/tag/v9.5.0

**Pull request merged**
