### PR TITLE
Scope search by key value on translation table

### PR DESCRIPTION
**Pull request by rafamds**

### CODE REVIEW

**Comment by dimsav** [comment]
Thanks for the PR. After giving a second thought I think this solution is quite custom to be in the package. With this scope we assume one knows exactly that it is required to pass an array with many specific keys, and I think this will confuse people.

**Comment by dimsav** [comment]
What if we change the scope to be used like this:

```php
Country::whereTrans('name', 'Portugal')->first(); // Takes the default locale

Country::whereTrans('name', 'Portugal', 'en')->first(); // Takes a custom locale
```

**Comment by rafamds** [comment]
That new suggestion of yours, would be better and cleaner in my opinion.

**Comment by dimsav** [comment]
Yep, this looks great. Can you please only do one change? Replace if(!is_null($locale)) with if ($locale)

Also can you write a test for each $locale case?

Thanks!

**Comment by rafamds** [comment]
Yes, I'll do that and submit a new PR with all this changes.

**Comment by dimsav** [comment]
:+1:

**Pull request closed without merging**
