### PR TITLE
Development

### PR DESCRIPTION
**Pull request by anzeznidarsic**
I was not able to run tests. Databases do not get generated. I tried with running phpunit inside of laravel-translatable folder but tables (migration table does) do not get generated. I would always get:

[04:08 PM ../laravel-translatable]$ phpunit
PHPUnit 4.6-ge85198b by Sebastian Bergmann and contributors.

Configuration read from /private/var/www/github/laravel-translatable/phpunit.xml

EE..E..EEEEEEEEE....EEEEEEEEEEEEEEEEE.EEEE.EEE

Time: 582 ms, Memory: 23.75Mb

There were 36 errors:

1) TestCoreModelExtension::it_saves_empty_instances
Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'translatable_test.companies' doesn't exist (SQL: insert into `companies` (`updated_at`, `created_at`) values (2015-01-30 15:08:47, 2015-01-30 15:08:47))
...

### CODE REVIEW

**Comment by anzeznidarsic** [comment]
I updated Translatable trait to PSR-2. That was wrong of me. Should I switch back or should we switch to PSR2?

**Comment by dimsav** [comment]
Let's not change to psr2 yet. If we do this, we should do it in a separate pr/issue.
If you have homestead on your pc, create a db named `translatable_test` and rerun the tests. Otherwise check the testbase to see the db connection required.

**Comment by anzeznidarsic** [comment]
I'll revert the psr2 changes.

I made local mysql database named translatable_test and changed username and password properly. The only thing that happens is that the "migrations" table gets created in translatable_test database.

**Comment by dimsav** [comment]
I guess solving that is part of the issue ;)

**Pull request closed without merging**
