### PR TITLE
Added fields selection to withTranslations method

### PR DESCRIPTION
**Pull request by Exitialis**

### CODE REVIEW

**Comment by pionl** [comment]
This is what I need, maybe would be easier to just allow custom builder?

@dimsav Any chance to be merged?

Thanks

**Comment by dimsav** [comment]
Thank you for the pr and sorry for the delay. All new features should be properly tested before adding to the package. Also please make sure StyleCI gets green again. 

Thanks!

**Comment by dronowar** [comment]
Please complete the pull with the fix from Luke265

**Comment by dimsav** [comment]
Closing because of missing tests.

**Pull request closed without merging**
