### PR TITLE
improve migration example

### PR DESCRIPTION
**Pull request by unitedworx**
improve migration example to move data from existing tables to the _translations table

### CODE REVIEW

**Comment by unitedworx** [comment]
I saw a lot of people asking how to handle moving data from their existing tables to the translations  tables so the goal of this example code is to nudge them in the right direction to handle this automatically via migrations

**Comment by dimsav** [comment]
Sorry I'm not keen on adding this into the default installation steps.

**Comment by dimsav** [comment]
Because is that it applies only if we have an existing project. We could add this info somewhere else in the docs though. I'll reopen to leave it as a reminder.

Thanks for the contribution!

**Comment by dimsav** [comment]
Readme was [just](https://github.com/dimsav/laravel-translatable/commit/ad136560f7b8fc3d017eac59837d26f4ac2e62f5) updated. Thanks!

**Comment by unitedworx** [comment]
Nice to see this added in documentation Dimitri. Incorporating these in migrations have helped me so far in several projects to move data from existing tables to the translation tables. so I just deploy mi code changes and run my migrations and my projects are multilingual ready :)

**Pull request closed without merging**
