### PR TITLE
add replicateWithTranslations function

### PR DESCRIPTION
**Pull request by simonfunk**

### CODE REVIEW

**Comment by dimsav** [comment]
Thanks for the PR. I just came back from Christmas vacation, will check soon!

**Comment by simonfunk** [comment]
yeah no problem ;)

**Comment by dimsav** [comment]
Can you please add some tests?

**Comment by markcameron** [comment]
Shame this was closed without being merged in. Really should be included since this is an extension of Eloquent. I believe it should be revisited.

**Comment by dimsav** [comment]
@markcameron feel free to add the tests :)

**Comment by mkwsra** [comment]
I really don't know what is the goal you guys are trying to achieve here, but @dimsav You are a great guy who wrote this module, right? you did a good job perhaps you can include this PR in a beta version or write the tests? or do whatever you like but please show your support to the community.

This feature has been there for a year!

Wish you a nice day, all of you

**Comment by dimsav** [comment]
@mkwsra thanks for your feedback. 

Will re-open this and hopefully somebody from the community will implement this with tests.

**Comment by simonfunk** [comment]
i wrote now the test, should be ready to implement now ;)
https://github.com/dimsav/laravel-translatable/pull/346

**Pull request closed without merging**
