### PR TITLE
Don't use fallback if record exists and the value is null

### PR DESCRIPTION
**Pull request by mohanklein**
When using a model with different translatable attributes, e.g. a required name & nullable description without a fallback dataset this change will return null instead of throwing a _'Trying to get property of non object'_ exception.

### CODE REVIEW

**Comment by mohanklein** [comment]
sorry I just updated the logic in a second commit ...

**Comment by dimsav** [comment]
can you make a test that describes the bug? sorry I'm still trying to understand, maybe I need more coffee

**Comment by plivius** [comment]
@dimsav @mohanklein 
I ran into the same issue, please see https://github.com/dimsav/laravel-translatable/pull/422 with phpunit test to illustrate the issue

**Comment by dimsav** [comment]
fixed in #422

**Pull request closed without merging**
