### PR TITLE
added basic tests for isDirty() and getDirty() behaviour

### PR DESCRIPTION
**Pull request by czim**
As requested in thread for issue #120

### CODE REVIEW

**Comment by dimsav** [comment]
Did you forget to push something? :P

**Comment by czim** [comment]
I don't think so, the only thing I added were two tests to demonstrate the (possibly) desired behaviour concerning isDirty and getDirty methods on models with translations. Those are in there, unless I'm very much mistaken?

**Comment by dimsav** [comment]
My apologies, I was not clear. 

> Good point. Can you send a PR with some tests?

Can you please send a PR with the implementation? Also do not forget the tests :)

**Comment by czim** [comment]
Ah, misunderstood you there indeed. I figured you didn't want me to mess around in the actual code.
I do not have a local 'fix' for this yet, just a work-around that I use. When I get some time available, I'll see about the writing the implementation; not sure when that will be though.

**Comment by dimsav** [comment]
Sorry, I have to close this. If somebody wants to implement it feel free to submit a full PR including implementation + tests.

**Pull request closed without merging**
