### PR TITLE
Allow Laravel 5.6

### PR DESCRIPTION
**Pull request by SjorsO**

### CODE REVIEW

**Comment by nousename** [comment]
Can this please be merged quickly

**Comment by dimsav** [comment]
For some reason the tests have not run and I would like to make sure everything passes before we release this. I could not run the tests locally because my php version needs to be updated.

**Comment by nousename** [comment]
ah ok weird
yes is just what I have also done, been updating to 5.6 and also needed an updated php version
thanks for the reply
________________________________

**Comment by SjorsO** [comment]
@dimsav 
I've ran the tests, turns out phpunit and orchestra/testbench also needed a version bump. I've updated them too.

image

**Comment by dimsav** [comment]
Thanks!

**Comment by dimsav** [comment]
New version was just tagged. Thank you all for your help.

**Pull request merged**
