### PR TITLE
Implement fallback option in case attribute returns empty value

### PR DESCRIPTION
**Pull request by k-zakhariy**
With this option we can have ability to get fallback value from fallback language in case
target language exists but attribute value is empty

### CODE REVIEW

**Comment by unitedworx** [comment]
Would be nice if this is added in! 

Solves a problem when some fields are translated and some are not and you end up with the website missing texts!

**Comment by dimsav** [comment]
I like the idea. We still need to update the docs, the configuration and write the tests in order to merge this.

**Comment by unitedworx** [comment]
@k-zakhariy it will be superb if you have time to amend the docs, configuration and tests for this pull request to be accepted by dimsav.

**Comment by k-zakhariy** [comment]
will push soon changes

**Comment by k-zakhariy** [comment]
Any updates on this ?

**Comment by dimsav** [comment]
Thanks a lot for your work. Will try to review this week.

**Comment by dimsav** [comment]
@k-zakhariy @unitedworx  I was thinking to leave out the per-model option. Do you guys have a use case in mind where you plan to have different per model configuration?

**Comment by k-zakhariy** [comment]
@dimsav I didn't use this ability in my project, for me its easy to declare options in config file.
I guess you need to think if this feature (per-model config) can be useful for some cases, in new projects

**Comment by unitedworx** [comment]
i will surely follow a project wide route, if you start having models behaving differently it might be confusing down the line.

**Comment by dimsav** [comment]
True, that's why I removed the per model config.

**Pull request merged**
