### PR TITLE
increase php minimum version

### PR DESCRIPTION
**Pull request by Gummibeer**
solves #462

### CODE REVIEW

**Comment by dimsav** [comment]
👍

**Comment by Gummibeer** [comment]
@dimsav after this is merged I would like to bring all type-hints and so on up to date.

**Comment by dimsav** [comment]
We rely on illuminate/support which requires "php": "^7.1.3", so this should be good to go.

**Comment by dimsav** [comment]
@Gummibeer feel free to merge ;-)

**Pull request merged**
