### PR TITLE
Used isTranslationAttribute method in setAttribute

### PR DESCRIPTION
**Pull request by Hyleeh**
A small but helpful refactor (at least for my case)
There is no harm in small bits of refactoring right:)

Thanks, Hyl

### CODE REVIEW

**Comment by Hyleeh** [comment]
Oops I forgot an 's' over there somewhere

**Comment by Hyleeh** [comment]
Added another similar change to isset

**Comment by dimsav** [comment]
Awesome, thanks!

**Comment by Hyleeh** [comment]
You are welcome! This helps me a lot^^

**Pull request merged**
